<?php

/**
 * This is the model base class for the table "mb_companies".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MbCompanies".
 *
 * Columns in table "mb_companies" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $cnpj
 * @property string $razao_social
 * @property string $endereco
 * @property string $email
 * @property integer $ativo
 * @property string $telefone
 * @property integer $alterador
 * @property string $data_criacao
 * @property string $data_alteracao
 *
 */
abstract class BaseMbCompanies extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mb_companies';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MbCompanies|MbCompanies', $n);
	}

	public static function representingColumn() {
		return 'cnpj';
	}

	public function rules() {
		return array(
			array('cnpj', 'required'),
			array('ativo, alterador', 'numerical', 'integerOnly'=>true),
			array('cnpj', 'length', 'max'=>20),
			array('razao_social, email, telefone', 'length', 'max'=>40),
			array('endereco', 'length', 'max'=>100),
			array('data_criacao, data_alteracao', 'safe'),
			array('razao_social, endereco, email, ativo, telefone, alterador, data_criacao, data_alteracao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, cnpj, razao_social, endereco, email, ativo, telefone, alterador, data_criacao, data_alteracao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'cnpj' => Yii::t('app', 'Cnpj'),
			'razao_social' => Yii::t('app', 'Razao Social'),
			'endereco' => Yii::t('app', 'Endereco'),
			'email' => Yii::t('app', 'Email'),
			'ativo' => Yii::t('app', 'Ativo'),
			'telefone' => Yii::t('app', 'Telefone'),
			'alterador' => Yii::t('app', 'Alterador'),
			'data_criacao' => Yii::t('app', 'Data Criacao'),
			'data_alteracao' => Yii::t('app', 'Data Alteracao'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('cnpj', $this->cnpj, true);
		$criteria->compare('razao_social', $this->razao_social, true);
		$criteria->compare('endereco', $this->endereco, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('ativo', $this->ativo);
		$criteria->compare('telefone', $this->telefone, true);
		$criteria->compare('alterador', $this->alterador);
		$criteria->compare('data_criacao', $this->data_criacao, true);
		$criteria->compare('data_alteracao', $this->data_alteracao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}