<?php

/**
 * This is the model base class for the table "mb_cars".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MbCars".
 *
 * Columns in table "mb_cars" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $placa
 * @property string $apelido
 * @property string $marca
 * @property string $modelo
 * @property integer $ativo
 * @property integer $alterador
 * @property string $data_criacao
 * @property string $data_alteracao
 *
 */
abstract class BaseMbCars extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mb_cars';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MbCars|MbCars', $n);
	}

	public static function representingColumn() {
		return 'placa';
	}

	public function rules() {
		return array(
			array('placa', 'required'),
			array('ativo, alterador', 'numerical', 'integerOnly'=>true),
			array('placa, apelido', 'length', 'max'=>20),
			array('marca, modelo', 'length', 'max'=>40),
			array('data_criacao, data_alteracao', 'safe'),
			array('apelido, marca, modelo, ativo, alterador, data_criacao, data_alteracao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, placa, apelido, marca, modelo, ativo, alterador, data_criacao, data_alteracao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'placa' => Yii::t('app', 'Placa'),
			'apelido' => Yii::t('app', 'Apelido'),
			'marca' => Yii::t('app', 'Marca'),
			'modelo' => Yii::t('app', 'Modelo'),
			'ativo' => Yii::t('app', 'Ativo'),
			'alterador' => Yii::t('app', 'Alterador'),
			'data_criacao' => Yii::t('app', 'Data Criacao'),
			'data_alteracao' => Yii::t('app', 'Data Alteracao'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('placa', $this->placa, true);
		$criteria->compare('apelido', $this->apelido, true);
		$criteria->compare('marca', $this->marca, true);
		$criteria->compare('modelo', $this->modelo, true);
		$criteria->compare('ativo', $this->ativo);
		$criteria->compare('alterador', $this->alterador);
		$criteria->compare('data_criacao', $this->data_criacao, true);
		$criteria->compare('data_alteracao', $this->data_alteracao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}